try:
    print(number)

except:
    print("error occurred")



try:
    numm1 = 39
    numm2 = 0
    print(numm1/numm2)

except:
    print("error occurred zero division error")
finally:
    print("success")

#throw
# tyes of errors

